language: node_js
node_js: "14"

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install -g elm@latest-0.19.1
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
